### ISSUE TITLE
kawa-scheme: issues executing code from files

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#348]
While the repl works, kawa-scheme has issues with basic hello world programs run from files, e.g.:

```
(display 42)
```

With this program, Doppio terminates before printing anything.

**Comment by perimosocordiae** [comment]
Note that the -e flag works:

```
$ ./doppio -jar kawa-2.0.jar -e '(display "hello\n")'
hello
```

**Comment by perimosocordiae** [comment]
After some head-scratching and source-code reading, I've found this:

```
$ ./doppio -jar kawa-2.0.jar --output-format scheme -f hello.scm 
hello
```

Looks like the bug is somewhere in how the default format is chosen. If we don't specify it, it defaults to "ignore", which ... ignores the output.

I'll check to see why that's happening, when the java version clearly chooses a different output format.

**Comment by perimosocordiae** [comment]
I may have posted too soon! Check out what the java version does:

```
$ java -jar kawa-2.0.jar --output-format ignore -f hello.scm 
hello
```

Now I'm really confused...

**Comment by perimosocordiae** [comment]
The docs (http://www.gnu.org/software/kawa/Named-output-formats.html) say that Java isn't buggy here: kawa isn't supposed to print top-level forms in scripts, which is why a script with just `'(42)` doesn't print anything. However, it _is_ supposed to honor direct calls to `display` and `write`, as in `(display 42)`.

Somehow, doppio is conflating the two, and ignoring output from direct calls to `display`. I'm not sure why.

**Comment by perimosocordiae** [comment]
As a test case, try the file:

```
(define (hello) (display "Hello\n"))
(hello)
```

Java prints "Hello", but doppio prints nothing.

**Comment by perimosocordiae** [comment]
It looks like a case of not flushing: adding the line `(flush-output-port)` to the last comment's program makes Doppio behave like native Java.

**Comment by perimosocordiae** [comment]
Aha! I figured it out! Here's a minimal test case:

```
class Test {
public static void main(String... args) {
  Runtime.getRuntime().addShutdownHook(new Thread() {
   public void run() {
    System.out.println("shutdown hook");
   }
  });
  System.out.println("Exiting...");
}
}
```

(Turns out, the flush gets called from a shutdown hook. Which we don't call, because the program doesn't ever explicitly call `System.exit()`...)

**Comment by jvilk** [comment]
I just checked; other VMs call `System.exit` when the VM quits to run shutdown hooks.

**Comment by perimosocordiae** [comment]
And _that_ bug is caused by a bug in our shutdown logic:

 * After adding the shutdown hook, we have two threads: [main, shutdown]
 * The main thread ends, and checks if there are other threads to run.
 * It sees the shutdown thread, which isn't a daemon, so it tries to schedule it.
 * The scheduler sees that the shutdown thread is in state NEW, and doesn't run it.
 * Execution ends without triggering any cleanup callbacks.

**Comment by perimosocordiae** [comment]
Fixed! Always fun to run into JVM behavior bugs when running large programs...
