### ISSUE TITLE
Upgrade to typescript v1.4

### ISSUE THREAD

**Issue by perimosocordiae** [plasma-umass/doppio#353]
Lots of cool features to use: http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx

**Comment by jvilk** [comment]
We have places in the code w/ comments begging for union types, and we can simplify all of our debug print logic using template logic.

We need to look at code generation for template strings, though, and ensure that template strings within debug messages stays within the debug messages, otherwise ice-cream won't strip it out!

**Comment by jvilk** [comment]
Yup, template strings work just fine.
