### ISSUE TITLE
support jxcore command line

### ISSUE THREAD

**Issue by Ben007** [plasma-umass/doppio#369]
I came across to a problem with node 0.10.38 and doppio.
```
node(45688,0x7fff78557300) malloc: *** error for object 0x3dc503571b70: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```
I saw the discussion from https://github.com/joyent/node/issues/9273 but Node 0.12 is not an option for me due to other deps. and I don't want to deploy two separate versions of node for a basic demo. I don't even know if it's doable this way. However I gave a shot with [jxcore master on github](https://github.com/jxcore/jxcore) and it went fine with v8 build. At the beginning I received another issue  then I've cleaned up everything and install the tools and deps using jx install. It doesn't crash anymore. 

I suspect if somehow npm compiles native addons using node 0.12 references because I had it installed and replaced back to 0.10. 

To use with jxcore I've also needed to update doppio from
```
node $(dirname $0)/build/release-cli/console/runner.js "$@"
```
to
```
jx $(dirname $0)/build/release-cli/console/runner.js "$@"
```

Now I'm able to run the my jar file using doppio on top of node 0.10.38 framework (but using jx binary). I'm no c++ or java expert and don't know much about the solution on the core but I would really like to have doppio working with node 0.10.x / jxcore without patching or forcing to upgrade node 0.12.

Anyway doppio is great and keep up the good work!

**Comment by jvilk** [comment]
Thanks for the compliments. I didn't think the upgrade would affect many people, since Doppio is intended to be used primarily in the browser -- after all, most people can simply run their favorite JVM natively on the command line if needed. :) The Node interface is used primarily for development purposes.

As indicated in the node bug, the segfaults are from a bug in Node v0.10's implementation of JavaScript strings. Conveniently, both JavaScript and the JVM use UTF-16 for strings, so Doppio goes ahead and converts string constants from JVM class files into JavaScript strings. I fixed a showstopping bug in this conversion process that prevented a core JVM class in JDK8 from functioning properly -- with rippling impacts that prevented things line `parseInt` from working!! (tl;dr: JDK8 uses a string to encode binary character set data as a string for some kooky reason; this data is used to convert characters to integers. Since the string is binary data in string form, it exercises a number of "fun" UTF-16 corner cases. Once fixed, the the segfaults began.)

Unfortunately, the segfault happens because Node has a bug in *its* string implementation. I lack the domain knowledge to fix or isolate the bug for them.

Now, Doppio does not need to eagerly convert all JVM string constants into JavaScript strings. JVM strings, including the weird character data string, are still represented as an array of bytes (actually, as an ArrayBuffer). However, we *do* need things like method and class names as JavaScript strings, as we use them in our bytecodes. There's no "flag" on these entries to differentiate them from string constants that are consumed primarily by JVM code, and changing string constant "resolution" to support two different use cases would complicate JVM logic in a number of places.

I may revisit this at another time, but I hope you understand that I have larger priorities at the moment.

**Comment by perimosocordiae** [comment]
If you've already gotten things working with jxcore (which it sounds like you have?), we'd be happy to keep a branch around with your changes. I agree that the node v0.12 requirement is a pain at moment.

**Comment by jvilk** [comment]
I suspect jxcore uses a different version of V8, and thus works because it's not buggy. The Node crash results from a buggy backported string fix from V8 trunk to Node v0.10's old version of V8.

**Comment by jvilk** [comment]
And yes, if jxcore support isn't too cumbersome, I'd be fine with supporting it -- it'd also make testing on SpiderMonkey from the command line feasible.

**Comment by Ben007** [comment]
@perimosocordiae I didn't do anything special, just updated the command-line to jx.

@jvilk Surely I can use 'java' command line instead but after troubling a lot with node 0.10 I'd started to use doppio command line to reproduce the problem. It saved a lots of time. 

Seems like there is not much change needed. I don't know how you could put 'jx' instead 'node' to the command line or if it's ever needed. Maybe you could simply add a note to somewhere that if anyone wishes to use it with node 0.10 and having a trouble with it. They can simply use it with jxcore or node 0.12.

Thanks
