### ISSUE TITLE
Latest version of DefinitelyTyped does not build with TS 1.4

### ISSUE THREAD

**Issue by mbebenita** [plasma-umass/doppio#376]
When I tried building Doppio, I ran into some problems compiling against the latest version of DefinitelyTyped. If TS is pinned to 1.4, DefinitelyTyped might need to be pinned to an older version as well.

**Comment by jvilk** [comment]
Thanks for the report. I fixed the build, so it should work now. You'll need to do a `bower update` to pull in the changes, I think.

(Also, in case you're noticing that the Travis-CI build fails, unit tests are failing because the version of the Java Class Library used by the `master` branch is out-of-date. I've fixed these problems in the `new-objects` branch, which will likely be merged into `master` sometime within the month.)
