### ISSUE TITLE
doppioh TypeScript generation

### ISSUE THREAD

**Issue by akadeev** [plasma-umass/doppio#386]
Seems this does not work in new-objects branch:
`./doppioh -classpath . -typescript build/dev-cli -d natives classes/util/Test`
`Error: Unable to read class file for Ljava/lang/Throwable;: TypeError: path must be a string`
Can you check it please? I would like to use a ts natives.

**Comment by jvilk** [comment]
I'm working on API improvements for native methods which will require some changes to `doppioh`, so I will check this out then!

**Comment by jvilk** [comment]
I'm still working on this. The new version will not require a `-typescript` flag, will not require you to `require()` a bunch of modules, and will rely on an upcoming NPM release of `doppio` for typing information -- so you can decouple your application and custom native methods from `doppio` itself.

I'll release an updated guide that uses the new API once I commit it. Sorry for the delay!

**Comment by jvilk** [comment]
The new version is committed, but I need to fix our unit tester before I'll have time to update the guide.

Also, I believe you need to pass in the path to `vendor/java_home/classes` on the classpath.

I'll keep this bug open, since that error message is not understandable. I will probably change `doppioh` to automatically add the Java Class Library to the classpath.

**Comment by jvilk** [comment]
@akadeev I just updated the guide and changed doppioh so it automatically searches the JCL. Let me know if you continue to experience issues!
