### ISSUE TITLE
Make listings.json leaner

### ISSUE THREAD

**Issue by jimfb** [plasma-umass/doppio#389]
Looking at the current release of doppio, it looks like the listings.json file is three-quarters of a megabyte, and includes things like `"GzipDemo.class":null,"GzipDemo.java":null`.

I admit I don't have a totally solid idea of what listings.json is trying to accomplish, but it seems unnecessarily bloated for someone who is trying to run a simple doppio instance.  Is there a way we could drastically cut down the size of this file (or maybe even eliminate it?).

**Comment by jvilk** [comment]
> I don't have a totally solid idea of what listings.json is trying to accomplish

It's consumed by the [`XMLHTTPRequest`-backed filesystem in BrowserFS](https://github.com/jvilk/BrowserFS/blob/master/src/backend/XmlHttpRequest.ts#L24), which requires a file index to operate so operations like `readdir` can function. Otherwise, there's no standard way to query a server for a file listing.

> It seems unnecessarily bloated for someone who is trying to run a simple doppio instance

You are absolutely correct. I never put any effort into minimizing it, because I planned to transition DoppioJVM to use JAR files. There were some serious stumbling blocks to completing that work, however, which I won't go into now -- because I've [recently](https://github.com/plasma-umass/doppio/commit/1fc96ed0c07351b9f60e5da6afc2d1ef434e0df6) [removed](https://github.com/plasma-umass/doppio/commit/121c00e48ecbdc48e2882bb14f00f079c47f6745) [them](https://github.com/plasma-umass/doppio/commit/8f2205fdfeec22e5852424312ced30de56f67877) in the `jar_jdk` branch. (Merging that branch is blocked on a few test failures I've yet to fix.)

That branch still requires a `listings.json` for the file system, but it is *much* smaller:

```
$ ls -lh listings.json
-rw-r--r--  1 jvilk  staff    11K Nov 15 13:12 listings.json
```

It can be made much smaller than that by:
* **Changing the representation to be more compact.** Since it is such a large listing, we use a verbose representation that is identical to what the XHR-backed file system requires in-memory to reduce startup time and to avoid engineering a transformation pass.
* **Supporting gzipped listings.** I'm pretty sure this will "just work", but I haven't tested it yet.

Also, I've been debating making common-case deployment super simple/plug-n-play via our now-standardized JDK. It seems like that might be useful.

**Comment by jimfb** [comment]
I enabled mod_deflate (gzip) in my apache config, and can confirm it does "just work" and dramatically cuts the file size (but slightly increases the parse time - still a worthwhile tradeoff).  Gzipped file size is ~150kb, which still seems large but makes the issue much less critical.

Ideally, perhaps the default system class loader would allow a URL directory, and the classloader could find classes as-needed by making web-requests.  But I can understand why having a directory listing (instead of guess-and-test) would be beneficial.

**Comment by jvilk** [comment]
I see what you mean. Here are some stumbling blocks to removing `listings.json` altogether, in the scenario where you are using the XHRFS:

* Right now, DoppioJVM explicitly uses `readdir` to enumerate and  `eval` native files (including its own) from the file system.
* The JCL reads some non-JAR files in the `java_home` directory (e.g. time zone data). I haven't explicitly checked, but I believe it performs `readdir` calls.

However, you don't actually need to use the XHRFS (and, consequently, `listings.json`). An alternative: you could use a single, large monolithic zip file that contains all of the data DoppioJVM needs, and mount it in the browser using BrowserFS's ZipFS. Another alternative: You could generate a list of files offline and include it in your JS file that constructs DoppioJVM, and preload them into a browser-local storage file system in BrowserFS. Another alternative: Cached the previously-mentioned ZIP file into browser-local storage to avoid file fetches on subsequent page loads, and use the information in `vendor/java_home/jdk.json` (which is produced for the `jar_jdk` branch) to determine when you need to update the cached data.

I'm considering adding a utility method on DoppioJVM and maybe some offline packaging scripts to facilitate some of this. I'd greatly appreciate hearing your feedback on what the ideal DoppioJVM deployment would be like. These are things I'd like to address before updating our hugely outdated demo at doppiojvm.org.

I'll also accept proposals on how to make the API easier to use. :)

**Comment by bertung** [comment]
Just an idea, running a post processor on source code to find out which classes are needed and create an lean listings.json output that lists just the classes needed to run the user application. That would dramatically reduce the file size, or not?

**Comment by jvilk** [comment]
The listings is a property of the `XmlHttpRequest` file system in BrowserFS, which requires a complete map of all files in the file system to support operations like `readdir`. Alternative file systems do not require this listing.

I will likely put together some example code that preloads the JCL and other materials into IndexedDB the first time DoppioJVM is constructed, preventing the need for `listings.json`. That is a cleaner model for most use cases.

**Comment by hrj** [comment]
Now that XHRFS allows listings to be specified in the constructor, the user can create `listings` at run-time, cache in IndexedDB, etc. Just saying, so that this issue can probably be closed now.

**Comment by jvilk** [comment]
Well, we could still make the listings smaller with a more compact representation. This issue is primarily concerned with the size of the listings.

**Comment by hrj** [comment]
Well, here's how I see it:

There are two concerns: `listings.json` as a file served over the network, and `listings` -- the in-memory representation of it.

For the in-memory representation, I don't think a significantly more compact form that is also quick to access is possible. The bulk of it is made of strings representing the directory and file names. One could try to de-dup the sub-strings, but accessing the structure would be slower.

For the large size of `listings.json` file, one immediate mitigation is to gzip it. The other is to use a zip filesystem. Yet another is to use a custom index format (if it happens to be more compact) and convert it to `listings` in-memory representation on the fly. The new XHFS constructor allows this third possibility.

**Comment by jvilk** [comment]
Closing this issue, as I think you're right -- it's not much of a problem anymore.
