### ISSUE TITLE
How to get the system classloader from a native function?

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#393]
I want to instantiate a Java object from my native method. Say the Java object is called `JO`.

`thread.getBsCl().getResolvedClass("JO")` returns null.

IIRC, the bootstrap class loader only loads classes which are part of the JRE. But `JO` is my custom class. To load it, I probably need to get the system class loader, right? How do I get it?

I tried looking at existing code to figure out, but all the native functions that I see in `src/natives` seem to return primitives, or strings, or array of primitives. Is that the way to solve this? Return primitives and construct the java object in Java-land?

Thanks!

**Comment by jimfb** [comment]
Returning primitives and strings, with the purpose of constructing a java object in java-land, would not work (I believe).  The reason is that you need to hold a reference to the original javascript object in order to prevent it from being garbage collected, and the JSVM does not provide a way to know when a javascript object is being garbage collected, so you can't know when to manually drop the reference.  For this reason, I think the java object needs to (internally) contain a reference to the javascript object.  That's my two cents.

**Comment by hrj** [comment]
Thanks @jimfb, but I didn't quite follow your response. Are you saying that the JS object could get garbage collected during the transmission from JS to Java-land?

------------

I am doing the following now:

```
    'evalRaw(Ljava/lang/String;)[Ljava/lang/Object;': function(thread, toEval) {
       var expr = toEval.toString()
       var res = eval(expr);
       return util.newArrayFromData(
         thread,
         thread.getBsCl(),
         '[Ljava/lang/Object;',
         [util.initString(thread.getBsCl(), typeof res), res]
       );   
     }
```

This native function evaluates the input string and returns the result and type to Java-land. The java-land caller then examines the type and stores the result internally in a java object. Seems to work fine.

I originally wanted to create the java object in JS itself, but haven't found a way so far.

**Comment by jvilk** [comment]
@hrj, you can get the system classloader with:

```{js}
thread.getJVM().getSystemClassLoader();
```

Alternatively, within Java, you can call `ClassLoader.getSystemClassLoader()`.

> Returning primitives and strings, with the purpose of constructing a java object in java-land, would not work (I believe).

I'm not sure I follow your logic, but you can indeed return primitives, strings, or complex Java objects created in a native method and use then in Java code with no issues.

You should be able to do what you want in the following manner:

```{js}
// If you are constructing an object, the class *must* be initialized!
var sysloader = thread.getJVM().getSystemClassLoader();
var cls = sysloader.getInitializedClass("J0");
if (cls === null) {
  // Class has not yet been initialized, so you need to use initializeClass instead, which is async.
} else {
  var J0 = cls.getConstructor(thread);
  var J0Obj = new J0(thread);
  // Call constructor method. You'll need the descriptor. This is a constructor w/o args.
  J0Obj['<init>()V'](thread, [] /* args */, function(err) {
    if (err) {
      // err is an JVM exception object; the constructor threw an exception.
    } else {
      // J0Obj is initialized, and can be returned to the program.
      thread.asyncReturn(J0Obj);
    }
  });
}
```

**Comment by jimfb** [comment]
I was working under the assumption that you were only able to pass primitives/strings, but not complex objects, into java land.  This is the situation for webworkers (I think), and I thought you were indicating a similar constraint across jvm/javascript.  If you can pass complex objects, there is no issue.

The following does still apply to webworkers, I believe?

What I was trying to say is, consider the object: `{foo: function(){}, bar: function(){}}`.  You can't serialize functions, so you would need to build an RPC interface.  If you wanted to reference that object using only primitives/strings/serializables, you could create an ID that uniquely identifies the object, as well as a description of the object's structure ("foo", "bar").  When java land accesses property "foo", you use the object ID to request the "foo" property off that object, and get a new ID that identifies the function.  Then Java land tries to invoke the function, and you use the function's ID to specify which function should be invoked in javascript land.  In theory, this could work.

The problem is: in Javascript land, you need a map of identifiers to objects.  But you don't know which identifiers are still valid, because there is no way of determining which identifiers have been garbage collected on the other side of the serialization boundary.  This means you need to keep all possible IDs forever, in case they're ever referenced in the future, but that would create a memory leak.

It sounds like this is not an issue for doppio, as per above, because it is possible to pass complex objects into java land.  I think this is an issue if running doppio in a webworker and it needs to reference javascript objects in the main thread.

Anyway, sorry for adding to the noise.  @jvilk's answer was obviously more useful :).

**Comment by hrj** [comment]
@jvilk Thanks for the detailed answer, I am able to get my class to load now.

@jimfb I can now see where your assumption came from. My phrasing of the question was a little terse; I just wanted to focus on the class loading part.

**Comment by jvilk** [comment]
@jimfb I'm not sure where you're coming from, but DoppioJVM's native methods and DoppioJVM itself should be located in the same program context -- so you will not be serializing items returned from a native method through a WebWorker message.

But if you wanted to serialize JVM objects over WebWorker messages, you could use any existing technologies that serialize JVM objects over network connections on other JVMs. For example, Java has the (Serializable)[https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html] interface and [CORBA](https://en.wikipedia.org/wiki/Common_Object_Request_Broker_Architecture).
