### ISSUE TITLE
Can the `responsiveness` setting be exposed through options?

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#404]
The `JVMThread.run()` method uses a `responsiveness` variable to break out of its while loop. If I understand right, this is a form of co-operative scheduling, where the thread yields to other threads (browser native event-loop or other JVM threads).

The `responsiveness` is hard-coded to `1000 ms`. Is this something that can be exposed via doppio options?

**Comment by jimfb** [comment]
Any idea why 1000ms was chosen?  That seems crazy long.  I would have expected a number closer to 50ms (or maybe even 10ms, in an attempt to avoid dropping any frames).

I also wonder if we would want to be able to change that value dynamically (can we set options at runtime or only startup?).  In particular, I can imagine that if there are no pending requests to the JVM, we might want responsiveness to be set to 10ms (be nice, avoid frame drops, initialize in the background) and when there are pending user requests we might be willing to eat a responsiveness of 150ms (or more) in order to minimize context switching overhead.  Seems like we would want to be able to control that based on a higher-level knowledge of what else is happening in the application.

**Comment by bertung** [comment]
If you look at the line where the responsiveness variable is used, it is not really a static 1000ms delay in all yields. If you keep it too low, starvation may occur more frequently stalling the browser.

**Comment by jvilk** [comment]
I chose 1000ms for throughput purposes. I realize it's less than ideal when running in the main thread, but figured users would normally run DoppioJVM in a WebWorker. I also anticipated eventually surfacing it as a configurable option if an interactive app needs to be more responsive to user input.

I don't have much time to commit to DoppioJVM over the next few weeks. I'll accept PRs for this feature if any of you are impatient to have it.

**Comment by hrj** [comment]
I will try to create a PR for configurable responsiveness. It seems easy to make it a static option. For making it dynamic, perhaps I can do this: If `typeof option == 'number'` then use it directly, else if it is a function, then call it and use its return value.

Aside, I just finished doing some benchmarking, with responsiveness = 50ms and 1000ms. The benchmark is a CPU intensive task that runs for about 30seconds. The overhead of `r=50ms` was less than `.1 %` over `r=1000ms`.
