### ISSUE TITLE
Force Synchronous Execution

### ISSUE THREAD

**Issue by jimfb** [plasma-umass/doppio#419]
Some operations need to be synchronous (for instance, an event handler needs to be synchronous in order to decide if the event bubbling should be canceled).

For such operations where synchronous behavior is absolutely essential, is it possible to add a mode whereby the scheduler will not yield control of the main thread back to the JSVM until the operation is complete?

cc @jvilk

**Comment by jvilk** [comment]
This would not be possible in the general case. It's not feasible to know if the JVM will need to yield. We yield to load in classes, to reset the stack depth, and to keep DoppioJVM responsive. You'd need to work around this restriction somehow.

**Comment by jvilk** [comment]
Some solutions, which aren't ideal but possible:

* You could stop bubbling every time, and re-apply the event if bubbling was desired.
* You could manually bubble the event up the DOM.

I'm not actually sure how to best expose the browser callback paradigm to the JVM, since you can't easily register a JVM function as a callback.
