### ISSUE TITLE
Update getting started guide

### ISSUE THREAD

**Issue by ianopolous** [plasma-umass/doppio#446]
I thoroughly enjoyed reading your paper. there are some very cool ideas in Doppio! 

I've been following along the instructions at:

https://github.com/plasma-umass/doppio/wiki/Doppio-Developer-Guide#plugging-doppiojvm-into-a-frontend

And it seems the doppio variable is not initialized in the browser, so neither the js or the cli calls work. 

I've tried comparing to the demo page, but that is too old to be a useful comparison. Any suggestions would be very much appreciated.

**Comment by jimfb** [comment]
@ianopolous Depending on what you're trying to do, you might find https://www.javapoly.com/ to be a convenient API for invoking Java in the browser/frontend.  If nothing else, you can look at the javapoly source code for an up-to-date example of starting up a doppio instance in the browser.

**Comment by jvilk** [comment]
Hmm, that's odd. The `doppio.js` file should expose a `doppio` global.

I will see about updating the documentation tomorrow and get back to you.

**Comment by ianopolous** [comment]
I've put up the webroot of my attempt here:
https://github.com/ianopolous/DoppioDemo

Apologies if I've done something stupid.

**Comment by jvilk** [comment]
You can see the source code and build instructions for an updated demo [here](https://github.com/jvilk/doppio-demo/tree/new-objects). The demo is not live yet because I am having issues with terminal emulation, and may need to switch to using a different library, but its DoppioJVM integration works. The magic happens [in this file](https://github.com/jvilk/doppio-demo/blob/new-objects/src/js/commands/java.ts), which may be a bit complex to look through.

> Apologies if I've done something stupid.

No need to apologize! Our documentation is out of date, and there are no simple examples to work from.

I changed the top-level variable to be `Doppio`, and the `JVM` constructor is `Doppio.VM.JVM`. I was trying to migrate toward loosely coupling DoppioJVM with Doppio, but forgot to update docs.

**Comment by ianopolous** [comment]
The new variable names fixed it. Thank you! Can't wait to get it all working!

**Comment by jvilk** [comment]
Awesome! Let me know if you have any questions. I'm reopening this so I remember to update the docs.

**Comment by jvilk** [comment]
The Getting Started Guide [is updated, and is now in Git](https://github.com/plasma-umass/doppio/tree/master/docs).
