### ISSUE TITLE
Missing class from Java core library

### ISSUE THREAD

**Issue by ianopolous** [plasma-umass/doppio#452]
I'm working from doppio.html at: https://github.com/ianopolous/Peergos/tree/doppio/ui

But it fails to load the javax.crypto.Mac class. However, this class is in the doppio/vendor/java_home/lib/jce.jar

**Comment by hrj** [comment]
The problem was with how we were defining the JVM options in Javapoly.

We were overriding the `bootstrapClasspath`, while specifying the `doppioHomePath` incorrectly. I have now fixed this in Javapoly and `javax.crypto.*` classes are being found correctly.

However, some javapoly classes are not being found by doppio. I suspect it has to do with some native code in javapoly.

Anyway, this issue can be closed I think.
