### ISSUE TITLE
Is there a way just download the dependenced class in jars

### ISSUE THREAD

**Issue by lixinlin** [plasma-umass/doppio#495]
when deploy the doppio webapp, so many and so big jars should be downloaded to client, it takes long time and no notice for the downloading event. Is there a way just download the dependenced class in jars?

**Comment by lixinlin** [comment]
Is there anyone has the same question?

**Comment by jvilk** [comment]
You could choose to re-package the JAR files to contain only the classes you think you need. Due to reflection, there's no magic tool that can figure out all of the dependencies that your project definitely needs.

As for no notice for the downloading event, the demo at https://doppiojvm.org/ does have a progress bar; it pre-loads the JARs into the file system before starting DoppioJVM. The code for that is at https://github.com/plasma-umass/doppio-demo
