### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by Horcrux7** [plasma-umass/doppio#514]
A status page with what is working, what is in development and what will never support will be nice.

Also which performance I can expect. How many slower will a app typical on the same hardware?

My current main question is which type of GUI is supported. A console application is nice, but not what people are looking for.

**Comment by jvilk** [comment]
Hello @Horcrux7,

You can find a list of what is not working in the GItHub issue tracker. 

Currently, no GUI interfaces are supported. [Someone added JavaFX support to a previous version of Doppio](https://github.com/plasma-umass/doppio/issues/373), but no one has put in any effort to port it to the latest master branch. [AWT is unsupported because it's infeasible to support without forking it](https://github.com/plasma-umass/doppio/issues/45#issuecomment-249943549). It may be feasible to support AWT in the future, but nothing is in development at the moment.

At the moment, I am the only maintainer, and have no free time to develop the project in any significant way until I complete my PhD in September. However, I am responsive to pull requests, and would be willing to advise anyone who puts in the effort to make a solid contribution to support any of those items.

Regarding performance, see [the evaluation in our academic paper](http://plasma-umass.org/doppio-demo/paper.pdf). Expect ~24-42x slowdown over the native HotSpot interpreter on compute-intensive applications. Much of this slowdown has to do with the fact that DoppioJVM lacks a comprehensive JIT, and that it has to emulate multiple threads on top of a single JavaScript thread due to limitations of the browser environment (see paper).

I hope that helps.
